# Railway Deployment Configuration for NEEX Backend

[build]
  builder = "heroku/buildpacks:20"
  buildCommand = "npm install"

[build.env]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "on-failure"
  workingDirectory = "/app"
